services:
  - type: web
    name: b-pot
    runtime: python
    plan: free
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: EMAIL_TO
        value: hsoomni@gmail.com
      - key: GEMINI_API_KEY
        sync: false
      - key: SHEETS_WEBHOOK_URL
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
