# Generated by Django 5.1.15 on 2026-06-18 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('brand', '브랜드'), ('personal', '개인')], max_length=20)),
                ('basic_info', models.JSONField(default=dict)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('answers', models.JSONField(default=list)),
                ('generated', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CTAInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(blank=True, choices=[('coffeechat', '커피챗'), ('campaign', '캠페인'), ('workshop', '워크숍')], max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('manager', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='core.result')),
            ],
            options={
                'verbose_name': 'CTA 문의',
                'verbose_name_plural': 'CTA 문의',
                'ordering': ['-created_at'],
            },
        ),
    ]
